
# This is a basic workflow to help you get started with Actions
name: CD
on:  
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which Env To Deploy
        options: 
        - dev
        - qa
        - stage
        - prod
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD
        run: |
         echo do a build

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: ${{ github.event.inputs.name }}
    needs: build-and-publish
    steps:
      - name: DEPLOY DEV
        run: |
          echo "deploy dev"
